# Generated by Django 4.0 on 2021-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_profile_direccion_profile_otros_profile_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
