# Generated by Django 4.0 on 2021-12-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_tipo_servicio_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['fecha', '-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
