# Generated by Django 4.0 on 2021-12-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_fecha_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
