# Generated by Django 4.0 on 2021-12-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_remove_pedidos_content_alter_pedidos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
