# Generated by Django 4.0 on 2021-12-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_pedidos_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='memorias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
