# Generated by Django 4.0.2 on 2022-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedidos_memorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('ganoper', models.BooleanField(default=False)),
                ('concep', models.CharField(blank=True, max_length=50, null=True)),
                ('importancia', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
