# Generated by Django 4.0.2 on 2022-03-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('canti', models.FloatField(blank=True, null=True)),
                ('ganper', models.BooleanField(default=False)),
                ('conce', models.CharField(blank=True, max_length=50, null=True)),
                ('importa', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
    ]
